# Editing
map cmd+z send_text all \x1f
map cmd+c send_text all \x1b[99~
map cmd+x send_text all \x1b[100~
map shift+enter send_text all \x1b\r

# Option
map alt+backspace send_text all \x1b\x7f
map alt+left send_text all \x1bb
map alt+right send_text all \x1bf
map alt+shift+left send_text all \x1b[1;4D
map alt+shift+right send_text all \x1b[1;4C

# Shift
map shift+left send_text all \x1b[1;2D
map shift+right send_text all \x1b[1;2C

# Command
map cmd+backspace send_text all \x15
map cmd+left send_text all \x01
map cmd+right send_text all \x05
map cmd+up send_text all \x1b[97~
map cmd+down send_text all \x1b[98~

# Command + Shift
map cmd+shift+left send_text all \x1b[1;10D
map cmd+shift+right send_text all \x1b[1;10C
map cmd+shift+up send_text all \x1b[1;10A
map cmd+shift+down send_text all \x1b[1;10B
