# See https://alacritty.org/config-alacritty.html

[general]
import = []
working_directory = "/Users/saltanovas/desktop/p"
live_config_reload = true
ipc_socket = true

[font]
# Perfect fit on x/y-axis using both 'Buttonless-Maximized' and 'Fullscreen' windows on my Mac
size = 17.0
normal = { family = "Monaco", style = "Regular" }
builtin_box_drawing = true

[window]
# "SimpleFullscreen" hides menu bar on ALL monitors
# "Fullscreen" does not make a window transparent, black just gets lighter
startup_mode = "Maximized" # Windowed | Maximized | Fullscreen | SimpleFullscreen
decorations = "Buttonless" # Full | None | Transparent | Buttonless

padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 1.0
blur = true
option_as_alt = "Both"

[scrolling]
history = 10000
multiplier = 1

[cursor]
style.shape = "Block"
style.blinking = "Never"
unfocused_hollow = true
thickness = 0.15

[bell]
animation = "EaseOut"
duration = 450
color = "#101010"

[terminal]
shell.program = "/opt/homebrew/bin/tmux"
shell.args = [
  "new-session",
  "-As", "p", # [a]ttach to the [s]ession 'p' if it exists or create it
  "-n", "main" # name the initial window 'main' if session is created
]
