map cmd+z         send_text all \x1f   # Undo
map alt+left      send_text all \eb    # Skip word left
map alt+right     send_text all \ef    # Skip word right
map cmd+left      send_text all \x01   # Home
map cmd+right     send_text all \x05   # End
map cmd+backspace send_text all \x15   # Delete line
map alt+backspace send_text all \e\x7f # Delete word
map shift+enter   send_text all \e\r   # New line