watch-later-dir=~/.local/state/mpv/watch_later

osc=no
ytdl-format=bestaudio
save-position-on-quit=yes

idle=yes
force-window=yes
keep-open=yes
auto-window-resize=no
autofit-larger=85%x85%
autofit-smaller=40%x40%
geometry=50%:50%
