" Editing
set hidden
set backspace=indent,eol,start
set mouse=a

" Indentation
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Search
set ignorecase
set smartcase
set incsearch
set hlsearch

" Appearance
set number
set cursorline
set cursorlineopt=number

syntax enable
if exists('+termguicolors')
    set notermguicolors
endif
colorscheme bat-base16


" Key mappings
let mapleader = " "
nnoremap <leader>w :write<CR>
nnoremap <leader>q :quit<CR>
nnoremap <leader>h :nohlsearch<CR>
nnoremap <leader>e :Explore<CR>