# ========================================
# 📟 Terminal
# ========================================
# Terminal emulator
cask "alacritty"
# Terminal multiplexer
brew "tmux"

# ========================================
# 🛠️ Shell Utilities
# ========================================
# Alternative to cat(1)
brew "bat"
# Alternative to find(1)
brew "fd"
# Fuzzy finder
brew "fzf"
# Tool for glamorous shell scripts
brew "gum"
# Alternative to grep(1)
brew "ripgrep"
# Simplified, community-driven man pages
brew "tlrc"
# Display directories as trees
brew "tree"

# ========================================
# 🕹 CLI Tools
# ========================================
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# GitHub command-line tool
brew "gh"
# A youtube-dl fork to download audio/video from YouTube and other sites
brew "yt-dlp"
# Quickly generate a disposable email using mail.tm API
brew "mailsy"
# Reverse proxy from a public endpoint to localhost
cask "ngrok"
# Password generator
brew "pwgen"
# RAR Archiver
cask "rar"
# 7-Zip archiver
brew "sevenzip"
# Internet file retriever
brew "wget"

# ========================================
# 📦 Languages & Runtimes
# ========================================
# AWS Cloud Development Kit - framework for defining AWS infra as code
brew "aws-cdk"
# Official Amazon AWS command-line interface
brew "awscli"
# GNU compiler collection
brew "gcc"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Platform built on V8 to build network applications
brew "node"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Python environment management
brew "pyenv"
# Development kit for the Java programming language
brew "openjdk@25"
# JDK from the Eclipse Foundation (Adoptium)
cask "temurin@21"
# JDK from the Eclipse Foundation (Adoptium)
cask "temurin@17"
# JavaScript package manager
brew "yarn"

# ========================================
# 🧰 GUI Tools
# ========================================
# Application uninstaller
cask "appcleaner"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Unpacks archive files
cask "the-unarchiver"

# ========================================
# 🖥️ Apps
# ========================================
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# App to write, plan, collaborate, and get organised
cask "notion"
# Replacement for Spotlight
cask "raycast"
# Music streaming service
cask "spotify"
# Media player
cask "vlc"
# Video communication and virtual meeting platform
cask "zoom"

# ========================================
# 🧑‍💻 Dev Apps
# ========================================
cask "jetbrains-toolbox"
cask "intellij-idea"
cask "datagrip"
cask "goland"
cask "orbstack"
cask "postman"
cask "visual-studio-code"

# ========================================
# 🔌 VS Code Plugins
# ========================================
# C/C++ language support
vscode "ms-vscode.cpptools"
# Go language support
vscode "golang.go"
# Java language support
vscode "redhat.java"
# Unofficial PHP language support
vscode "DEVSENSE.phptools-vscode"
# Python language support
vscode "ms-python.python"
# TypeScript Next features
vscode "ms-vscode.vscode-typescript-next"
# XML language support
vscode "redhat.vscode-xml"
# YAML language support
vscode "redhat.vscode-yaml"
# Prettier code formatter
vscode "esbenp.prettier-vscode"
# Unofficial shell script formatter
vscode "foxundermoon.shell-format"
# Binary Plist viewer and editor
vscode "dnicolson.binary-plist"
# Live server for static & dynamic pages
vscode "ritwickdey.liveserver"
# GitHub Copilot inline coding suggestions
vscode "github.copilot"
# GitHub Copilot chat
vscode "github.copilot-chat"
