# Configuration options: https://github.com/tldr-pages/tlrc#configuration-options
[cache]
dir = "~/.cache/tlrc"
# Update once every 30 days
max_age = 720
# Language resolution is priority-based, left to right.
languages = ["custom", "en"]
